import './globals.css'
import {Inter} from 'next/font/google'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Landing Page',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <main className={'max-w-[1366px] min-h-screen mx-auto py-0 px-[60px] flex flex-col justify-between'}>
            <Navbar/>
            {children}
            <Footer/>
        </main>
        </body>
        </html>
    )
}
